[versions]

androidPlugin = "7.3.1"
composeCompiler = "1.3.1"
composeJb = "1.2.0"
detekt = "1.21.0"
kotlin = "1.7.10"

[libraries]

androidx-activityCompose = { module = "androidx.activity:activity-compose", version = "1.6.0" }
androidx-appcompat = { module = "androidx.appcompat:appcompat", version = "1.5.1" }
detekt-plugins-formatting = { module = "io.gitlab.arturbosch.detekt:detekt-formatting", version.ref = "detekt" }

[plugins]

android-application = { id = "com.android.application", version.ref = "androidPlugin" }
android-library = { id = "com.android.library", version.ref = "androidPlugin" }
compose = { id = "org.jetbrains.compose", version.ref = "composeJb" }
detekt = { id = "io.gitlab.arturbosch.detekt", version.ref = "detekt" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlin-multiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
versions = { id = "com.github.ben-manes.versions", version = "0.43.0" }