build:
  maxIssues: 0

complexity:
  LongMethod:
    active: false
  LongParameterList:
    active: false

formatting:
  FinalNewline:
    active: false
    autoCorrect: true
    insertFinalNewLine: true
  MaximumLineLength:
    active: true
    maxLineLength: 180
  NoWildcardImports:
    active: false
  ArgumentListWrapping:
    active: true
    maxLineLength: 180
  ParameterListWrapping:
    active: true
    maxLineLength: 180
  NoEmptyFirstLineInMethodBlock:
    active: false
  TrailingCommaOnCallSite:
    active: true
    autoCorrect: true
    useTrailingCommaOnCallSite: true
  TrailingCommaOnDeclarationSite:
    active: true
    autoCorrect: true
    useTrailingCommaOnDeclarationSite: true

style:
  MagicNumber:
    active: false
    ignoreAnnotated:
      - 'Preview'
  MaxLineLength:
    active: true
    maxLineLength: 180
  NewLineAtEndOfFile:
    active: false
  WildcardImport:
    active: false
  UnusedPrivateMember:
    active: true
    ignoreAnnotated:
      - 'Preview'

naming:
  FunctionNaming:
    ignoreAnnotated: [Composable]
  TopLevelPropertyNaming:
    constantPattern: '[A-Z][_A-Za-z0-9]*'
    propertyPattern: '[A-Za-z][_A-Za-z0-9]*'
    privatePropertyPattern: '_?[A-Za-z][_A-Za-z0-9]*'