name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:

  detekt:
    name: Detekt
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Change wrapper permissions
        run: chmod +x ./gradlew
      - name: Detekt
        uses: gradle/gradle-build-action@v3
        with:
          arguments: detekt

  assemble-lib:
    name: Assemble Lib
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Change wrapper permissions
        run: chmod +x ./gradlew
      - name: Assemble
        uses: gradle/gradle-build-action@v3
        with:
          arguments: :lib:assemble

  tests:
    name: Test
    needs: [ assemble-lib ]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Change wrapper permissions
        run: chmod +x ./gradlew
      - name: Assemble
        uses: gradle/gradle-build-action@v3
        with:
          arguments: allTests

  assemble-demo:
    name: Assemble Demo
    needs: [ assemble-lib ]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Change wrapper permissions
        run: chmod +x ./gradlew
      - name: Assemble Desktop
        uses: gradle/gradle-build-action@v3
        with:
          arguments: :demo-desktop:assemble
      - name: Assemble Android
        uses: gradle/gradle-build-action@v3
        with:
          arguments: :demo-android:assemble
      - name: Assemble Web
        uses: gradle/gradle-build-action@v3
        with:
          arguments: :demo-web:assemble
