name: CI

on:
  pull_request:
    branches: [ main ]

  workflow_dispatch:

concurrency:
  group: ${{ github.head_ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Verify code correctness
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac # v4
      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '11'
      - name: Change wrapper permissions
        run: chmod +x ./gradlew
      - name: Init gradle
        run: ./gradlew init
      - name: Detekt
        run: ./gradlew detekt
      - name: Assemble
        run: ./gradlew assemble
      - name: Test
        run: ./gradlew allTests
